
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd2?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root

  profiles:
    active: '@env@'

nacos:
   msg: testmsg

