spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd1?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root

nacos:
  msg: devmsg